name: Linter and test check
on: push
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  make-lint:
    # Name the Job
    name: Runs super-linter
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # installing dependencies
      - name: Install Dependencies
        run: make install

      # Runs the Linter action
      - name: Run super-linter
        run: make lint
      - name: Run jest
        run: make test
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
